# Generated by Django 4.2.5 on 2023-09-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('jefe_directo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.CharField(choices=[('buen estado', 'Buen estado'), ('mal estado', 'Mal estado'), ('en reparacion', 'En reparación')], default='Buen estado', max_length=15)),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('dañado', 'Dañado'), ('reparacion', 'Reparación')], default='Disponible', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sede')),
            ],
        ),
    ]
