# Generated by Django 4.2.3 on 2023-08-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('danado', 'Dañado'), ('reparacion', 'Reparación')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='estado',
            field=models.CharField(choices=[('buen_estado', 'Buen estado'), ('mal_estado', 'Mal estado'), ('en_reparacion', 'En reparación')], default='Buen estado', max_length=15),
        ),
    ]
