# Generated by Django 4.2.5 on 2023-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('prestado', 'Prestado'), ('dañado', 'Dañado'), ('reparacion', 'Reparación')], default='Disponible', max_length=20),
        ),
    ]
