# Generated by Django 4.2.3 on 2023-08-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elemento',
            old_name='Disponibilidad',
            new_name='disponibilidad',
        ),
    ]
