# Generated by Django 4.2.5 on 2023-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_elemento_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Dañado', 'Dañado'), ('Reparacion', 'Reparación')], default='Disponible', max_length=20),
        ),
    ]
