# Generated by Django 4.2.3 on 2023-09-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Prestado', 'Prestado'), ('Disponible', 'Disponible'), ('Dañado', 'Dañado'), ('En reparación', 'En reparación'), ('En mantenimiento', 'En mantenimiento'), ('En baja', 'En baja')], default='Disponible', max_length=20)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.elemento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
