# Generated by Django 4.2.3 on 2023-09-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
    ]
